version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:3001
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
    depends_on:
      - backend
    networks:
      - synagogue-network

  # Backend NestJS API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - HEBCAL_API_KEY=${HEBCAL_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - synagogue-network

  # Admin Dashboard
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile.dev
    ports:
      - '3002:3002'
    volumes:
      - ./apps/admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:3001
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
    depends_on:
      - backend
    networks:
      - synagogue-network

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - synagogue-network

  # Nginx for local development (optional)
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - synagogue-network
    profiles:
      - with-nginx

volumes:
  redis_data:

networks:
  synagogue-network:
    driver: bridge